services:
  next-recette:
    image: ghcr.io/taco-greco/next-cda25/next:${IMAGE_TAG:-latest}
    container_name: next-cda25-recette
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      APP_ENV: recette